version: '3.4'
services:
  php-fpm:
    container_name: php-fpm
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    links:
      - mysql
  nginx:
    container_name: role_nginx
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
    ports:
      - 80:80
    links:
      - php-fpm
  mysql:
    image: mysql:8.0.28
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33061:3306 #for local phpstorm access
    environment:
      MYSQL_DATABASE: role_app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/datadir:/var/lib/mysql
